apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: vulnapps-dev
spec:
  selector:
    matchLabels:
      app: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: harbor-01a.livefire.solutions/vulnerableapps/drupal:8.5.0
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - couchdb
                  topologyKey: "kubernetes.io/hostname"
