apiVersion: v1
kind: Service
metadata:
  name: drupal
  namespace: vulnapps-dev
  labels:
    app.kubernetes.io/name: drupal
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.100.51
  ports:
  - port: 80
  selector:
    app: drupal

